More settings options
SquonSerq/replay-recorder pull request #11
Opened 2022-01-09 17:51 UTC by SquonSerq

Allows making checkboxes to configure Danser inside Settings frame.

2022-01-09 18:00 UTC, SquonSerq commented
Need to delete all danser related files such as logs and settings before merging.

2022-01-09 18:07 UTC, RetteraDev commented on danser/danser.log
> +2022/01/09 23:34:42 -------------------------------------------------------------------
А зачем нам лог в коммите?

2022-01-09 18:07 UTC, RetteraDev commented on danser/settings/default.json
> +		"OsuSongsDir": "D:/osu!/Songs",
Отказались же заливать json, нет? Почему конфиг в коммите

2022-01-09 18:07 UTC, RetteraDev commented on pages/settings.py
> +		i = 0
Лучше переименовать в какой-нибудь row_number

2022-01-09 18:07 UTC, RetteraDev commented on models/config.py
> +from tkinter import StringVar, BooleanVar, IntVar
IntVar не используешь еще, в этот коммит можно не добавлять было

2022-01-09 18:07 UTC, RetteraDev commented on models/config.py
> +				"frame_name": "Sliders snake in",
Почему frame_name? Мы же не создаем под каждую настройку новый фрейм, это просто селектор или поле для ввода же
Скорее description назвать или setting_name

2022-01-09 18:07 UTC, Qu1s commented on models/config.py
> +				"field": "In"
Зачем это поле я не понимаю
Я считаю нам нужно в выбранных нами настройках, которые будем делать изменяемыми хранить информацию:
setting_name - то, что напишем в интерфейсе рядом с полем для ввода, своего рода коментарий за что отвечает галочка
type - тип настройки
root - соответствие с полем этой настройки из конфига денсера

Зачем field и obj в дальнейшем добавляется я тоже не понял

2022-01-09 18:07 UTC, Qu1s commented on pages/settings.py
> +			Checkbutton(self, text=v["frame_name"],
Далеко не все настройки у нас булевы, нельзя просто так взять и поставить Checkbutton

2022-01-09 18:07 UTC, Qu1s commented on pages/settings.py
> +			variable=v["obj"],
Можно в качестве переменной поставить сразу значение v['root'], он изменит значение в нашем конфиге в программе, не запишет в json

2022-01-09 18:07 UTC, Qu1s commented on pages/settings.py
> +			command=lambda: self.controller.config.update_from_frame(v["obj"], root, field)).grid(row=4+i, column=0)
Если в variable подставится значение уже в конфиг (Например сразу в self.danser_config['Objects']['Sliders']['Snaking'] запишется, то нам и command не нужен

2022-01-09 18:08 UTC, SquonSerq commented on danser/settings/default.json
> +		"OsuSongsDir": "D:/osu!/Songs",
Два ласт коммита (удалил лог и конфиг)

2022-01-09 18:08 UTC, SquonSerq commented on danser/danser.log
> +2022/01/09 23:34:42 -------------------------------------------------------------------
Два ласт коммита (удалил лог и конфиг)

2022-01-09 18:09 UTC, SquonSerq commented on pages/settings.py
> +		i = 0
Переименовал

2022-01-09 18:10 UTC, SquonSerq commented on models/config.py
> +from tkinter import StringVar, BooleanVar, IntVar
Потом все равно будет использоваться (это уже точно), я эту ветку доделывать буду, в таком состоянии не залью

2022-01-09 18:11 UTC, SquonSerq commented on models/config.py
> +				"frame_name": "Sliders snake in",
Справедливо. Переименовал в setting_name

2022-01-09 18:17 UTC, SquonSerq commented on models/config.py
> +				"field": "In"
В `obj` мы храним непосредственно значение, которое мы потом используем в tkinter объекте через `variable` аргумент.
`type` нам нужен для инициализации `obj`.
`root` и `field` нужны нам для получения ссылки на нужное поле в `config.danser_config`. Если мы кладем в root просто `self.danser_config['Objects']['Sliders']['Snaking']['In']`, то мы получаем копию примитива в поле, а если мы выставляет `root` и `field`, и потом акссесим через `root[field]`, то мы обращаемся по ссылке к `config.danser_config` в нужные поля.

2022-01-09 18:18 UTC, SquonSerq commented on pages/settings.py
> +			Checkbutton(self, text=v["frame_name"],
Согласен, тут будет if на определенные типы переменных

2022-01-09 18:19 UTC, SquonSerq commented on pages/settings.py
> +			variable=v["obj"],
Если мы просто поставим переменную не через TkinterVar, то у нас не обновится элемент Tkinter.

Также тут ты не понял, что такое рут, расписал выше.

2022-01-09 18:20 UTC, SquonSerq commented on pages/settings.py
> +			command=lambda: self.controller.config.update_from_frame(v["obj"], root, field)).grid(row=4+i, column=0)
Опять же, если мы поставим в `variable` значение не через TkinterVar, то у нас не будут обновляться элементы, так как ткинтер может отлавливать только изменение собственных переменных.

2022-01-09 18:21 UTC, Qu1s commented on models/config.py
> +from tkinter import StringVar, BooleanVar, IntVar
Хорошо, закрывай этот поинт

2022-01-09 18:28 UTC, Qu1s commented on models/config.py
> +				"field": "In"
>то мы получаем копию
Ну понятно, передается только значение
Вот почему нельзя как в плюсах-то по ссылке? Досадно
В таком случае предлагаю оставить комментарий на эту тему, для потомков, которые захотят (а может и смогут) переписать это место

2022-01-10 14:38 UTC, Qu1s requested changes

2022-01-10 14:38 UTC, Qu1s commented on utils/controller.py
> +			self.set_window_size(600, 230)
Я думаю, такие вещи стоит указать непосредственно в классе Settings самому фрейму задать размер при его инициализации, а не указывать его каждый раз при нажатии кнопки

2022-01-10 14:38 UTC, Qu1s commented on utils/controller.py
> +									-skin="{self.config.skin_name.get()}" \
По-моему, у тебя строки слишком вправо уехали, или это тут так отображается?

2022-01-10 14:38 UTC, Qu1s commented on utils/controller.py
> +		while True:
Лучше бесконечные циклы не юзать, думаю вот так

```
out = 'start'
while not "Finished" in str(out):
    out_text.set(out)
    print(out)
    out = p.stdout.readline()

new_window.update()
```

После этого можно будет убрать строку `out_text.set("start")`

2022-01-10 14:38 UTC, Qu1s commented on utils/controller.py
> +		self.app.maxsize(width, height)
No new line at end of file
Просто пустую строку в конце файла нужно оставлять. Раньше из-за этого ты мог себе ОС сломать, потому что раньше окончание файла чекалась по переносу строки и отсутствию данных после него. Но это так, предыстория
Сейчас просто хорошая привычка

2022-01-10 14:38 UTC, Qu1s commented on models/config.py
> +				"field": "In"
Этот поинт можно закрыть

2022-01-10 14:42 UTC, SquonSerq commented on utils/controller.py
> +		self.app.maxsize(width, height)
Fixed.

2022-01-10 14:46 UTC, SquonSerq commented on utils/controller.py
> +		while True:
Согласен. Fixed.

2022-01-10 14:46 UTC, SquonSerq commented on utils/controller.py
> +									-skin="{self.config.skin_name.get()}" \
Сделал меньше табуляцию. Fixed.

2022-01-10 14:53 UTC, SquonSerq commented on utils/controller.py
> +			self.set_window_size(600, 230)
Согласен. Перенес размеры окон в сами фреймы, изменил контроллер, чтобы брал размеры оттуда при изменении.

2022-01-10 15:00 UTC, Qu1s commented on utils/controller.py
> +			if "Finished" in str(out):
Нам условие с брейком не нужно, while в следующей итерации сам чекнет это и не пойдет внутрь

2022-01-10 15:00 UTC, Qu1s approved these changes

2022-01-10 15:02 UTC, merged