feature: new interface for main menu
SquonSerq/replay-recorder pull request #20
Opened 2022-01-15 06:20 UTC by RetteraDev

Create new interface for main frame

Was founded some bugs is process:
1) When db exists and is actual we can't start render. It's endless [https://github.com/SquonSerq/replay-recorder/issues/18](url)
2) Program is not in bottom task panel. It's consequence of self.overrideredirect(1), that removes win frame [https://github.com/SquonSerq/replay-recorder/issues/19](url)

2022-01-15 11:29 UTC, SquonSerq reviewed
Доделывай абстракции, потому что иначе такое не добавить, слишком много ответственностей в объектах, к которым они не имеют отношения

2022-01-15 11:29 UTC, SquonSerq commented on app.py
> +		app_name = tk.Label(top_bar, text='Replay Recorder', **frame_lg_bg_style, fg=light_white)
Не лучше ли будет под этот лейбл сделать отдельный стиль, который будет содержать и bg, и fg?

2022-01-15 11:29 UTC, SquonSerq commented on pages/main_menu.py
> +		self.db = sqlite3.connect("./danser/danser.db")
Не приведет ли этот коннект к блокировке файла дб, из-за чего дансер не сможет обратиться к файлу?

2022-01-15 11:29 UTC, SquonSerq commented on pages/main_menu.py
> +				print(f'{beatmap_data[0]} - {beatmap_data[1]}[{beatmap_data[2]}].  Played by {replay_data.player_name} on {replay_data.timestamp}')
Я думаю, лучше вынести логику связанную с дб в отдельный класс, потому что иначе наш View получает ответственность, которой у него быть не должно.

2022-01-15 11:29 UTC, SquonSerq commented on pages/main_menu.py
> +				image_tk = ImageTk.PhotoImage(image.resize((160, 90)))
То же самое с изображениями, лучше вынести в отдельную абстракцию.

2022-01-15 11:29 UTC, SquonSerq commented on pages/main_menu.py
> +				print(f'{beatmap_data[0]} - {beatmap_data[1]}[{beatmap_data[2]}].  Played by {replay_data.player_name} on {replay_data.timestamp}')
Более того, возможно, запросы надо сделать асинхронными, потому что при больших входных данных программа может встать

2022-01-15 13:38 UTC, RetteraDev commented on pages/main_menu.py
> +		self.db = sqlite3.connect("./danser/danser.db")
В последнем коммите инициализация базы идет после конфига, так что норм

2022-01-15 13:38 UTC, RetteraDev commented on app.py
> +		app_name = tk.Label(top_bar, text='Replay Recorder', **frame_lg_bg_style, fg=light_white)
Сделал

2022-01-15 13:38 UTC, RetteraDev commented on pages/main_menu.py
> +				print(f'{beatmap_data[0]} - {beatmap_data[1]}[{beatmap_data[2]}].  Played by {replay_data.player_name} on {replay_data.timestamp}')
Обсудили, что не нужно

2022-01-17 08:27 UTC, SquonSerq reviewed
Доделывай, еще много чего надо править

2022-01-17 08:27 UTC, SquonSerq commented on utils/colors.py
> +label_lg_bg_style = {
Наверно, стоит переименовать этот стиль и на 22 строке, потому что они содержат не только `background` параметр

2022-01-17 08:27 UTC, SquonSerq commented on utils/controller.py
> +		self.render = Render(self.render_queue, self.output_queue)
Депенденси инжекшн, конечно, круто, но думаю строки `21, 22, 23` можно упаковать в класс рендера

2022-01-17 08:27 UTC, SquonSerq commented on utils/controller.py
> +	def get_beatmap_data(self, beatmap_hash):
Какой смысл было выносить DB Access класс отдельно, если ты назначаешь здесь функции, которые в итоге используют этот класс? Можно обойтись без этого метода по прямому вызову DB из контроллера, так очевиднее будет

2022-01-17 08:27 UTC, SquonSerq commented on utils/controller.py
> +	def add_replay_to_render(self, frame, replay_path, selected_skin):
Точно также, как и выше. Какой смысл было выделять рендерер отдельным классом, если ты в итоге функцию на него здесь добавляешь. Лучше обработку эту засунуть непосредственно в класс, отвечающий за это и вызывать его с параметрами напрямую

2022-01-17 08:27 UTC, SquonSerq commented on utils/controller.py
> +		for replay_data in self.render_list:
Зачем нам проходить по всем элементам массива, если мы все равно рендерим последний в листе? Лучше сразу брать элемент на 0 позиции и рендерить его. После рендера просто удалять плей из списка на рендер.

2022-01-17 08:27 UTC, SquonSerq commented on utils/controller.py
> +		for replay_data in self.render_list:
К тому же мутабельность `self.render_list` может привести к неоднозначным последствиям имхо.

2022-01-17 08:27 UTC, SquonSerq commented on utils/db_controller.py
> +class Db():
Лучше назвать DaoDB (Data Access Object DB), лучше передает смысл класса, чем просто DB. Название файла изменить на DaoDB соответственно

2022-01-17 08:27 UTC, SquonSerq commented on utils/read_queue.py
> +class Render(threading.Thread):
Классы вроде не называются глаголами, так что лучше изменить названия класса на что-то другое, например, `Renderer` или что-то подобное, что больше будет отражать класс как сущность

2022-01-17 08:27 UTC, SquonSerq commented on utils/read_queue.py
> +class Render(threading.Thread):
Класс также надо вынести в отдельный файл с его соответственно названием.

2022-01-17 08:27 UTC, SquonSerq commented on utils/read_queue.py
> +class Render(threading.Thread):
Если ты начал выносить сюда всю логику рендера, то справедливо будет вынести вообще ВСЮ логику, связанную с рендером, в этот класс (render_list и тд)

2022-01-17 08:27 UTC, SquonSerq commented on utils/read_queue.py
> +					replay_data['frame'].children['!progressbar']['value'] = int(re.search("Progress: ([0-9]*)%", line).group(1))
Не очень хорошо, что ты прямо здесь меняешь вьюшку, это не очень очевидно. Лучше как-то придумать, как менять вьюшку непосредственно в отведенном под нее пространство.

2022-01-18 12:03 UTC, SquonSerq requested changes
Переделай названия, архитектура в принципе норм, надо будет немного изменить, я сам потом этим попробую заняться

2022-01-18 12:03 UTC, SquonSerq commented on utils/controller.py
> +		self.dao = Dao()
Здесь можно просто `db` назвать переменную, будет лучше понятно

2022-01-18 12:03 UTC, SquonSerq commented on utils/controller.py
> +	def start_render_if_db_loaded(self):
Не думаю, что стоит называть переменную с условием, потому что у нас нет условия, когда рендер начинается без загрузки дб. Оставь просто `start_render_queue` или просто `start_render`

2022-01-18 12:03 UTC, SquonSerq commented on utils/dao.py
> +class Dao():
Лучше все-таки назвать `DaoDB`, потому что Data Access Object не обязательно указывает на DB

2022-01-18 12:03 UTC, SquonSerq commented on utils/renderer.py
> +	def add_replay_to_render(self, frame, replay_path, selected_skin):
Если реплей добавляется в очередь на рендер, которая еще не идет, то просто `add_to_queue` или `add_replay_to_queue`

2022-01-18 12:03 UTC, SquonSerq commented on utils/renderer.py
> +		self.selected_replays = []
Переименуй лучше в waiting_replays или че-то такое, чтобы было понятно, что они ждут на рендер пойти

2022-01-18 12:03 UTC, SquonSerq commented on utils/renderer.py
> +		self.queue = queue.Queue()
Тут понятнее будет render_queue, чтобы показать, что это не просто какая-то очередь, а что она конкретно отвечает уже за рендер

2022-01-18 12:03 UTC, SquonSerq commented on utils/renderer.py
> +	def render_video(self):
Тут лучше будет имхо переименовать в start_render_process

2022-01-18 12:03 UTC, SquonSerq commented on utils/controller.py
> +	def start_render_if_db_loaded(self):
Да, тут лучше будет `start_render`

2022-01-18 12:06 UTC, SquonSerq commented on utils/renderer.py
> +	def add_replay_to_render(self, frame, replay_path, selected_skin):
или `add_to_waiting_queue`

2022-01-18 20:47 UTC, RetteraDev commented on utils/renderer.py
> +	def add_replay_to_render(self, frame, replay_path, selected_skin):
add_replay_to_queue

2022-01-18 21:03 UTC, RetteraDev commented on utils/renderer.py
> +		self.selected_replays = []
added_replays

2022-01-19 13:35 UTC, SquonSerq approved these changes
LGTM

2022-01-19 13:35 UTC, merged